import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getSession } from "@/libs/getSession";
import { logout } from "@/libs/action";
import GithubLink from "@/components/GithubLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="absolute top-0 w-full">
          <ul className="flex flex-row justify-start items-center gap-4 p-4">
            <li>
              <Link href="/">Home</Link>
            </li>
            {!session ? (
              <>
                <li>
                  <Link href="/register">Register</Link>
                </li>
                <li>
                  <Link href="/login">Login</Link>
                </li>
              </>
            ) : (
              <>
                <li>
                  <Link href="/dashboard">Dashboard</Link>
                </li>
                <li className="ml-auto">
                  <form action={logout}>
                    <button className="px-4">Log out</button>
                  </form>
                </li>
              </>
            )}
          </ul>
        </nav>
        <GithubLink />
        {children}
      </body>
    </html>
  );
}
